# Generated by Django 2.2.4 on 2020-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='菜单名称')),
                ('permissions', models.CharField(max_length=50, verbose_name='权限')),
                ('url', models.CharField(max_length=100, verbose_name='链接index')),
                ('type', models.SmallIntegerField(choices=[(0, '菜单'), (1, '按钮')], verbose_name='菜单类型')),
                ('parent', models.CharField(default='', max_length=30, verbose_name='父菜单')),
                ('icon', models.CharField(default='menu-icon fa fa-pencil-square-o', max_length=100, verbose_name='图标')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
    ]
