# Generated by Django 2.2.4 on 2020-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(blank=True, max_length=50, verbose_name='server_id')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('server_type', models.CharField(blank=True, max_length=20, verbose_name='server_type')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='hostname')),
                ('ip1', models.CharField(blank=True, max_length=50, verbose_name='ip')),
                ('ip2', models.CharField(blank=True, max_length=50, verbose_name='ip')),
                ('in_service', models.CharField(blank=True, max_length=10, verbose_name='in_service')),
                ('service_level', models.CharField(blank=True, max_length=40, verbose_name='service_level')),
                ('site', models.CharField(blank=True, max_length=20, verbose_name='site')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='os')),
                ('cpu', models.CharField(blank=True, max_length=5, verbose_name='cpu')),
                ('mem', models.CharField(blank=True, max_length=5, verbose_name='mem')),
                ('platform_support', models.CharField(blank=True, max_length=100, verbose_name='platform_support')),
                ('app_support', models.CharField(blank=True, max_length=100, verbose_name='app_support')),
                ('disk', models.CharField(blank=True, max_length=10, verbose_name='disk')),
                ('business_contact', models.CharField(blank=True, max_length=100, verbose_name='business_contact')),
                ('it_contact', models.CharField(blank=True, max_length=100, verbose_name='it_contact')),
                ('modify_time', models.CharField(blank=True, max_length=20, verbose_name='modify_time')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('server_id',),
            },
        ),
    ]
